# Generated by Django 4.0.6 on 2022-07-22 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aksara', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Test',
            new_name='TestModel',
        ),
    ]
