# Generated by Django 4.0.6 on 2022-12-26 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aksara", "0002_catalogjson"),
    ]

    operations = [
        migrations.AddField(
            model_name="catalogjson",
            name="file_src",
            field=models.CharField(default="", max_length=400),
        ),
    ]
