# Generated by Django 4.0.6 on 2022-07-22 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aksara', '0002_rename_test_testmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestModel',
        ),
    ]
