# Generated by Django 4.0.6 on 2022-07-22 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aksara', '0003_delete_testmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaJson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dashboard_name', models.CharField(max_length=200)),
                ('dashboard_meta', models.JSONField()),
            ],
        ),
    ]
