# Generated by Django 4.0.6 on 2023-01-03 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aksara", "0004_catalogjson_catalog_category_name_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="KKMNowJSON",
            new_name="DashboardJson",
        ),
    ]
