# Generated by Django 4.0.6 on 2022-09-16 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aksara', '0005_kkmnowjson'),
    ]

    operations = [
        migrations.AddField(
            model_name='kkmnowjson',
            name='chart_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
