# Generated by Django 4.0.6 on 2022-09-29 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aksara', '0007_kkmnowjson_chart_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KKMNowJSON',
        ),
    ]
